# Workflow for deploying to Azure Web App
name: Build and deploy Python app to Azure Web App - sai-balusu-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      # Optional: Add a step to run tests if you have them
      # - name: Run tests
      #   run: |
      #     pytest

      - name: Create necessary files for Azure deployment
        run: |
          # Create a startup command file
          # Change this line in your workflow file
          echo "gunicorn --bind=0.0.0.0 --timeout 600 run:app" > startup.sh
          chmod +x startup.sh
          
          # Create a .env file with environment variables
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          
          # Create an empty uploads directory if it doesn't exist
          mkdir -p src/static/uploads

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/
            !**/__pycache__/
            !**/*.pyc
            !**/*.pyo
            !**/*.pyd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sai-balusu-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          
      - name: 'Configure Azure Web App Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'sai-balusu-website'
          app-settings-json: |
            [
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "0"
              },
              {
                "name": "SECRET_KEY",
                "value": "${{ secrets.SECRET_KEY }}"
              },
              {
                "name": "ADMIN_USERNAME",
                "value": "${{ secrets.ADMIN_USERNAME }}"
              },
              {
                "name": "ADMIN_PASSWORD",
                "value": "${{ secrets.ADMIN_PASSWORD }}"
              }
            ]
        id: settings
